#!/bin/sh

IFACE="eth0"
IFACE_IP_ADDR="10.0.0.71/24"
IFACE_GW_ADDR="10.0.0.1"

case "$1" in
    start)
        echo -n "Setting ip address: "
        ip link set $IFACE up
        ip addr add $IFACE_IP_ADDR dev $IFACE
        ip route add default via $IFACE_GW_ADDR dev $IFACE
    ;;
    stop)
        echo -n "Removing ip address: "
        ip addr flush dev $IFACE
        ip link set $IFACE down
        ip route del default via $IFACE_GW_ADDR dev $IFACE
    ;;
    restart|force-reload)
        echo -n "Reloading modules: "
        ip addr flush dev $IFACE
        ip link set $IFACE down
        ip link set $IFACE up
        ip addr add $IFACE_IP_ADDR dev $IFACE
        ip route del default via $IFACE_GW_ADDR dev $IFACE
        ip route add default via $IFACE_GW_ADDR dev $IFACE
    ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
    ;;
esac

exit 0
